src/client/app/project/create/create.controller.js, src/client/app/project/create/create.module.js, src/client/app/project/create/home.controller.js, src/client/app/project/manage/manage.module.js, src/client/app/project/manage/multiple.controller.js, src/client/app/project/manage/single.controller.js, src/client/app/project/project.module.js, src/client/app/project/project.service.js, src/client/index.html
@tladendo for your review.  The project module and project services moved
=> Add projects module

README.md, config/index.js, gulp.config.js
Just the start of using env configuration during the build process.  Need to add the ability to define angular constants via the build.
=> Using env configuration usage

src/client/app/app.module.js, src/client/app/getting-started/getting-started.controller.js, src/client/app/getting-started/getting-started.jade, src/client/app/getting-started/getting-started.module.js, src/client/app/getting-started/getting-started.route.js, src/client/app/index.jade, src/client/app/layout/views/main.jade, src/client/app/project/create/create.route.js, src/client/app/project/create/submit/submit.html, src/client/app/project/manage/manage.route.js, src/client/app/project/manage/multiple.html, src/client/app/project/project.module.js
fyi @indytechcook @vietnogi – this turns the getting-started module into a proper Angular module and turns the shell into a shell for ui-router. I still need to make it so that we can dynamically inject the mock stuff, but this took me longer to figure out than I thought it would.
=> Tom fix routing

.gitignore, gulp.config.js, gulpfile.js, karma.conf.js, package.json, src/client/app/core/core.route.spec.js, src/client/app/project/create/scripts/create.route.spec.js, src/client/app/project/manage/scripts/manage.route.spec.js, src/client/app/project/manage/scripts/multiple.controller.spec.js
Some changes to the test runner.  There is a inject issue with the create project test.  Not sure why yet.
=> DEM-10 Test Runner working with jenkinds

src/client/app/core/core.route.spec.js
hey @indytechcook @vietnogi -- I think you'll like this. Once I get Rohit's microservice integrated, I'm going to clean up the unit test stuff and get more coverage. This is definitely temporary, but it fixes the build! :)
=> Fixed the build

gulp.config.js, src/client/app/project/project.service.js, src/client/app/project/project.stub.js
=> Made mocks match actual endpoints

gulp.config.js, gulpfile.js, src/client/app/index.jade, src/client/app/project/project.service.js, src/client/app/project/project.stub.js, src/client/nostubs/project.nostub.js
yo @indytechcook @vietnogi check it out
=> Tom add microservice backend

src/client/app/core/styles/_mixins.scss, src/client/app/create-account/styles/create-account.scss, src/client/app/create-account/views/create-account.jade, src/client/app/layout/styles/form.scss, src/client/app/layout/styles/header.scss, src/client/app/layout/styles/modal.scss
=> add icons to valid/invlaid stat

src/client/app/create-account/scripts/create-account.controller.js, src/client/app/index.jade
=> arrange stuff in jade

src/client/app/index.jade
=> add media query to comment

src/client/app/app.module.js, src/client/app/create-account/scripts/create-account.module.js, src/client/app/create-account/styles/create-account-desktop.scss, src/client/app/create-account/styles/create-account.scss, src/client/app/create-account/views/create-account.jade, src/client/app/index.jade, src/client/app/layout/scripts/layout.module.js, src/client/app/layout/styles/form.scss, src/client/app/layout/styles/main.scss, src/client/app/layout/styles/modal.scss, src/client/app/login/scripts/login.controller.js, src/client/app/login/scripts/login.module.js, src/client/app/login/scripts/login.route.js, src/client/app/login/styles/login.landscape.scss, src/client/app/login/styles/login.scss, src/client/app/login/views/login.jade
=> Login page

bower.json, src/client/app/core/core.module.js, src/client/app/core/resource/resource.api.service.js, src/client/app/core/resource/resource.module.js
@tladendo and @vietnogi 
I wanted to show you the direction I was going.  I'm adding tests now.
This is a factory for creating resources. It would be used like this:
First, the individual services would register themselves with the API:
```javascript
api.add('work');
// OR
api.add({
resource: 'work',
url: '/work'
});
// OR
api.add({
resource: 'work',
url: '/users/:user_id/work',
params: {
user_id: '@user_id'
}
});
```
Then api service would be used like this in a controller:
```javascript
api.work.get.$promise.then(function () {});
```
Next I'm adding a data provider which can be used to resolve in routes.
=> Base API resource

src/client/app/layout/styles/form.scss, src/client/app/submit-work/about-project/about-project.route.js, src/client/app/submit-work/about-project/scripts/elevator-pitch.controller.js, src/client/app/submit-work/about-project/styles/elevator-pitch.scss, src/client/app/submit-work/about-project/views/elevator-pitch.jade, src/client/app/submit-work/includes.jade
ping @indytechcook & @tladendo 
page: /#/submit-work/about/elevator-pitch
=> [DEM-140] Elevator Pitch page

src/client/app/submit-work/about-project/styles/competitors.scss, src/client/app/submit-work/about-project/views/brief.jade, src/client/app/submit-work/about-project/views/competitors.jade, src/client/app/submit-work/about-project/views/elevator-pitch.jade, src/client/app/submit-work/about-project/views/name.jade, src/client/app/submit-work/includes.jade
ping @tladendo & @indytechcook
=> [DEM-127] Links to similar apps

src/client/app/submit-work/includes.jade, src/client/app/submit-work/users/styles/users.scss, src/client/app/submit-work/users/views/users.jade
=> [DEM-126] Your Apps Users page

src/client/app/feature/feature.module.js, src/client/app/feature/feature.service.js, src/client/app/feature/feature.service.spec.js, src/client/app/submit-work/features/scripts/features.controller.js, src/client/app/submit-work/submit-work.module.js, src/client/app/submit-work/submit-work.service.js
Adding a features Service and updated the submit controllers
cc @tladendo @vietnogi @r-jain
=> Features service

src/client/app/index.jade, src/client/app/work-request/includes.jade, src/client/app/work-request/work-request.spec.js, src/client/app/work-request/work-request.stubs.js
Adds in work request tests
cc @tladendo @vietnogi @r-jain
=> Add tests for work request

src/client/app/core/resource/resource.data.provider.js
@tladendo @vietnogi @r-jain 
Reformatted data provider.  This makes it actually work.
=> Reformatted data provider

src/client/app/layout/styles/form.scss, src/client/app/submit-work/includes.jade, src/client/app/submit-work/launch/styles/success.scss, src/client/app/submit-work/launch/views/success.jade
Ping @indytechcook & @tladendo
=> [DEM-152] success page

src/client/app/getting-started/views/getting-started.jade, src/client/app/layout/views/header.jade, src/client/app/login/scripts/login.controller.js, src/client/app/login/scripts/login.module.js, src/client/app/login/scripts/login.service.js
@tladendo @vietnogi @r-jain auth fixes and build fixes.
=> Auth fixes

src/client/app/submit-work/about-project/scripts/brief.controller.js, src/client/app/submit-work/about-project/views/brief.jade, src/client/app/submit-work/designs/scripts/designs.controller.js, src/client/app/submit-work/designs/scripts/designs.controller.spec.js, src/client/app/submit-work/designs/views/designs.jade, src/client/app/submit-work/features/scripts/features.controller.js, src/client/app/submit-work/features/scripts/features.controller.spec.js, src/client/app/submit-work/features/views/features.jade
fyi @indytechcook @vietnogi -- this makes ui integration more or less complete. waiting on backend changes so i can persist the filename stuff.
=> Tom complete ui integration

src/client/app/submit-work/about-project/views/brief.jade, src/client/app/submit-work/designs/scripts/designs.controller.js, src/client/app/submit-work/designs/views/designs.jade
fyi @indytechcook @vietnogi -- just making sure we have 'upload' placeholders for the demo
=> Added file upload placeholders

src/client/app/app.module.js, src/client/app/core/resource/resource.data.provider.js, src/client/app/index.jade, src/client/app/view-work/scripts/view-work-multi.controller.js, src/client/app/view-work/scripts/view-work-multi.controller.spec.js, src/client/app/view-work/scripts/view-work-single.controller.js, src/client/app/view-work/scripts/view-work-single.controller.spec.js, src/client/app/view-work/scripts/view-work.module.js, src/client/app/view-work/scripts/view-work.routes.js, src/client/app/view-work/views/view-work-multiple.jade, src/client/app/view-work/views/view-work-single.jade, src/client/app/work-request/work-request.spec.js, src/client/app/work-request/work-request.stubs.js
DEM-112 Add Work Request Pages
@tladendo @vietnogi 
Initial pages with real data.  Needs visual stuff but it works.
=> DEM-112 Add Work Request Pages

bower.json, src/client/app/bowers.jade, src/client/app/layout/styles/header.landscape.scss, src/client/app/layout/styles/main.scss, src/client/app/submit-work/aside/submit-work-aside.directive.js, src/client/app/submit-work/aside/submit-work-aside.jade, src/client/app/submit-work/aside/submit-work-aside.scss, src/client/app/submit-work/launch/styles/estimate.scss, src/client/app/submit-work/scroll-state.directive.js, src/client/app/submit-work/submit-work.jade, src/client/app/submit-work/submit-work.module.js, src/client/app/submit-work/submit-work.scss
=> [DEM-187] Navigation Logic to Scroll

src/client/app/layout/scripts/layout.module.js, src/client/app/submit-work/aside/submit-work-aside.directive.js, src/client/app/submit-work/submit-work.jade
=> [DEM-187] bug fix and hash anchor feature

.jscsrc, gulpfile.js, src/client/app/core/resource/resource.api.service.js, src/client/app/core/resource/resource.data.provider.js, src/client/app/feature/feature.service.js, src/client/app/feature/feature.service.spec.js, src/client/app/layout/scripts/layout.module.js, src/client/app/login/scripts/login.controller.js, src/client/app/login/scripts/login.module.js, src/client/app/submit-work/about-project/scripts/brief.controller.spec.js, src/client/app/submit-work/about-project/scripts/competitors.controller.spec.js, src/client/app/submit-work/about-project/scripts/elevator-pitch.controller.spec.js, src/client/app/submit-work/about-project/scripts/name.controller.spec.js, src/client/app/submit-work/about-project/scripts/type.controller.spec.js, src/client/app/submit-work/designs/scripts/designs.controller.spec.js, src/client/app/submit-work/features/scripts/features.controller.js, src/client/app/submit-work/features/scripts/features.controller.spec.js, src/client/app/submit-work/launch/scripts/estimate.controller.js, src/client/app/submit-work/launch/scripts/estimate.controller.spec.js, src/client/app/submit-work/launch/scripts/success.controller.spec.js, src/client/app/submit-work/next/next.directive.js, src/client/app/submit-work/submit-work.service.js, src/client/app/submit-work/submit-work.service.spec.js, src/client/app/submit-work/users/scripts/users.controller.spec.js, src/client/app/view-work/scripts/view-work-multi.controller.js, src/client/app/view-work/scripts/view-work-multi.controller.spec.js, src/client/app/view-work/scripts/view-work-single.controller.spec.js, src/client/app/view-work/views/view-work-multiple.jade, src/client/app/work-request/work-request.spec.js, src/client/app/work-request/work-request.stubs.js
Fixing some tests and jshint issues
@tladendo @vietnogi
=> Dem 222 Failing tests

src/client/app/layout/styles/form.scss, src/client/app/submit-work/about-project/styles/type.scss, src/client/app/submit-work/about-project/views/competitors.jade, src/client/app/submit-work/about-project/views/name.jade, src/client/app/submit-work/about-project/views/type.jade, src/client/app/submit-work/aside/submit-work-aside.jade, src/client/app/submit-work/designs/views/designs.jade, src/client/app/submit-work/features/views/features.jade, src/client/app/submit-work/launch/views/estimate.jade, src/client/app/submit-work/next/next-state.jade, src/client/app/submit-work/users/views/users.jade
=> [DEM-181] Copy should match the latest copy

src/client/app/submit-work/about-project/scripts/type.controller.js, src/client/app/submit-work/about-project/views/type.jade
merging as per prasad's req -- this is really small anyway
=> Tom dem 206 type

src/client/app/submit-work/aside/submit-work-aside.directive.js, src/client/app/submit-work/aside/submit-work-aside.jade, src/client/app/submit-work/features/scripts/features.controller.js, src/client/app/submit-work/submit-work.service.js, src/client/app/submit-work/submit-work.service.spec.js
fyi @vietnogi @indytechcook -- now updating prices in real-time. The `save` stuff is a little messy, but basically, the local version of `features` is different from what the API expects because it has a few extra fields that are useful to us. Anyway, this both calculates price locally and updates it based on API responses.
=> Tom dem 226 dynamic price

src/client/app/submit-work/about-project/styles/brief.scss, src/client/app/submit-work/about-project/views/brief.jade, src/client/app/submit-work/users/styles/users.scss, src/client/app/submit-work/users/views/users.jade
=> [DEM-236] Show current character count in submit-work text boxes

src/client/app/submit-work/submit-work.service.js, src/client/app/submit-work/submit-work.service.spec.js, src/client/app/submit-work/users/views/users.jade
=> Removed minlength from users

src/client/app/submit-work/about-project/scripts/competitors.controller.js
=> Disallow blank similar app names

src/client/app/feature/feature.service.js, src/client/app/feature/feature.service.spec.js
Update feature listing
@appirio-tech/demandside
=> DEM-259 Update feature listing

src/client/app/submit-work/launch/views/estimate.jade
Change "launch" to "submit"
@appirio-tech/demandside
=> DEM-253:  Change "launch" to "submit"

src/client/app/layout/styles/form.scss
=> [DEM-264] Cancel button on PROJECT BRIEF

src/client/app/submit-work/about-project/styles/type.scss, src/client/app/submit-work/about-project/views/brief.jade
going to auto merge since simple stuff.
=> [DEM-265] project type color change

src/client/app/submit-work/about-project/views/name.jade, src/client/app/submit-work/aside/estimate.filter.js, src/client/app/submit-work/aside/submit-work-aside.desktop.scss, src/client/app/submit-work/aside/submit-work-aside.directive.js, src/client/app/submit-work/aside/submit-work-aside.filter.js, src/client/app/submit-work/aside/submit-work-aside.jade, src/client/app/submit-work/aside/submit-work-aside.scss, src/client/app/submit-work/includes.jade, src/client/app/submit-work/submit-work.service.js, src/client/app/submit-work/submit-work.service.spec.js
DEM-254 Aside name changes
this is @tifletcher branch.  It works so i'm submitting the request
@appirio-tech/demandside
=> DEM-254 Aside name changes

gulpfile.js
@vietnogi and @tladendo 
Replaces image urls with cdn prefix in template cache
=> Update img relpace

src/client/app/submit-work/aside/submit-work-aside.directive.js, src/client/app/submit-work/aside/submit-work-aside.jade
Update aside price to use local calculation
cc @tladendo @vietnogi
=> Update aside price to use local calculation

src/client/app/submit-work/about-project/scripts/brief.controller.js, src/client/app/submit-work/about-project/scripts/competitors.controller.js, src/client/app/submit-work/about-project/scripts/name.controller.js, src/client/app/submit-work/about-project/scripts/type.controller.js, src/client/app/submit-work/about-project/views/brief.jade, src/client/app/submit-work/about-project/views/competitors.jade, src/client/app/submit-work/about-project/views/name.jade, src/client/app/submit-work/about-project/views/type.jade, src/client/app/submit-work/aside/submit-work-aside.jade, src/client/app/submit-work/designs/scripts/designs.controller.js, src/client/app/submit-work/designs/views/designs.jade, src/client/app/submit-work/features/scripts/features.controller.js, src/client/app/submit-work/features/views/features.jade, src/client/app/submit-work/launch/scripts/estimate.controller.js, src/client/app/submit-work/launch/styles/estimate.scss, src/client/app/submit-work/launch/views/estimate.jade, src/client/app/submit-work/scroll-state.directive.js, src/client/app/submit-work/submit-work.controller.js, src/client/app/submit-work/submit-work.jade, src/client/app/submit-work/submit-work.scss, src/client/app/submit-work/submit-work.service.js, src/client/app/submit-work/submit-work.service.spec.js, src/client/app/submit-work/users/scripts/users.controller.js, src/client/app/submit-work/users/views/users.jade
=> [DEM-283]  Refactor name & type page validation

src/client/app/submit-work/about-project/scripts/type.controller.js, src/client/app/submit-work/about-project/views/brief.jade, src/client/app/submit-work/aside/submit-work-aside.directive.js, src/client/app/submit-work/aside/submit-work-aside.jade, src/client/app/submit-work/aside/submit-work-aside.scss, src/client/app/submit-work/launch/scripts/estimate.controller.js, src/client/app/submit-work/launch/views/estimate.jade, src/client/app/submit-work/scroll-state.directive.js, src/client/app/submit-work/submit-work.controller.js, src/client/app/submit-work/submit-work.jade, src/client/app/submit-work/submit-work.scss, src/client/app/submit-work/submit-work.service.js
=> [DEM-227] check buttons for nav

src/client/app/blocks/logger/logger.js, src/client/app/getting-started/views/getting-started.jade
=> pre-demo fixes

src/client/app/layout/styles/form.scss, src/client/app/submit-work/about-project/styles/brief.scss, src/client/app/submit-work/about-project/views/brief.jade
=> Changed next button to anchor

src/client/app/submit-work/about-project/scripts/competitors.controller.js, src/client/app/submit-work/about-project/views/competitors.jade
=> Removed placeholder on similar apps once one has been added

src/client/app/submit-work/features/styles/features.desktop.scss, src/client/app/submit-work/features/styles/features.scss, src/client/app/submit-work/features/views/features.jade
=> [DEM-280] feature page - add new feature area not per spec

src/client/app/submit-work/designs/styles/designs.scss, src/client/app/submit-work/designs/views/designs.jade
=> Added '(optional)'

src/client/app/submit-work/aside/submit-work-aside.desktop.scss
=> [DEM-278] features page alignment on the image that appears on hoover

src/client/app/index.jade, src/client/app/layout/scripts/modal.directive.js, src/client/app/layout/styles/main.scss, src/client/app/layout/styles/modal.scss, src/client/app/layout/views/shell.jade, src/client/app/submit-work/launch/scripts/estimate.controller.js, src/client/app/submit-work/launch/styles/estimate.scss, src/client/app/submit-work/launch/views/estimate.jade
=> [DEM-202] Modal directive and terms n conditions

src/client/app/submit-work/users/views/users.jade
=> Removed char count from users

src/client/app/submit-work/features/scripts/features.controller.js, src/client/app/submit-work/features/views/features.jade
=> [DEM-280] "additional features" for features

gulpfile.js, package.json
=> [DEM-307] Fix Gulp to not crash from a jade/scss compile error

src/client/app/layout/scripts/modal.directive.js, src/client/app/submit-work/aside/submit-work-aside.jade, src/client/app/submit-work/aside/submit-work-aside.scss, src/client/app/submit-work/features/scripts/features.controller.js, src/client/app/submit-work/features/styles/features.landscape.scss, src/client/app/submit-work/features/styles/features.scss, src/client/app/submit-work/features/views/features.jade, src/client/app/submit-work/launch/views/estimate.jade
=> [DEM-278] Change feature example from aside to centered modal.

src/client/app/submit-work/about-project/views/competitors.jade
=> Hide similar apps title before user input

src/client/app/submit-work/submit-work.service.js
=> Fixed persistence

gulp.config.js, gulpfile.js, package.json, src/client/app/submit-work/includes.jade, src/client/app/submit-work/submit-work.controller.coffee
=> [DEM-307] Set Gulp to compile coffee

src/client/app/submit-work/about-project/scripts/brief.controller.js, src/client/app/submit-work/about-project/scripts/competitors.controller.js, src/client/app/submit-work/about-project/scripts/name.controller.js, src/client/app/submit-work/about-project/scripts/type.controller.js, src/client/app/submit-work/about-project/views/brief.jade, src/client/app/submit-work/about-project/views/competitors.jade, src/client/app/submit-work/about-project/views/name.jade, src/client/app/submit-work/about-project/views/type.jade, src/client/app/submit-work/aside/submit-work-aside.directive.js, src/client/app/submit-work/designs/scripts/designs.controller.js, src/client/app/submit-work/designs/views/designs.jade, src/client/app/submit-work/features/scripts/features.controller.js, src/client/app/submit-work/launch/scripts/estimate.controller.js, src/client/app/submit-work/launch/scripts/success.controller.js, src/client/app/submit-work/launch/views/estimate.jade, src/client/app/submit-work/next/next.directive.js, src/client/app/submit-work/scroll-state.directive.js, src/client/app/submit-work/submit-work.service.js, src/client/app/submit-work/users/scripts/users.controller.js, src/client/app/submit-work/users/views/users.jade
@appirio-tech/demandside updated as per discussion. doing away w/ hoisting in favor of `var` for functions, and using `vm` over `$scope`
=> Dem 233 scope

src/client/app/submit-work/submit-work.service.js
@appirio-tech/demandside refactor of the way we clean up the `work` object fields before `POST`/`PUT`
=> refactored method for removing superfluous fields from work obj

src/client/app/submit-work/about-project/views/type.jade
=> copy change

src/client/app/submit-work/submit-work.service.js
=> Refactored service to match standards

gulpfile.js, src/client/app/timeline/styles/timeline.landscape.scss, src/client/app/timeline/styles/timeline.scss
ping at @appirio-tech/demandside
=> [DEM-313] timeline center fix

src/client/app/index.jade
=> [DEM-313] fix build

gulp.config.js, gulpfile.js, src/client/app/index.jade
=> [DEM-313] build fix #2

src/client/app/submit-work/launch/launch.route.js
=> Fixed broken submit

src/client/app/submit-work/about-project/scripts/brief.controller.js, src/client/app/submit-work/about-project/views/brief.jade, src/client/app/submit-work/designs/scripts/designs.controller.js, src/client/app/submit-work/designs/specs/designs.controller.spec.js, src/client/app/submit-work/designs/views/designs.jade
=> Add file upload feature to client app

bower.json, src/client/app/layout/views/header-nav.jade, src/client/app/scripts/project-details.routes.js, src/client/app/scripts/projects.routes.js
=> Use latest copilot release

src/client/app/submit-work/about-project/scripts/brief.controller.js, src/client/app/submit-work/about-project/views/brief.jade, src/client/app/submit-work/designs/scripts/designs.controller.js, src/client/app/submit-work/designs/views/designs.jade, src/client/app/submit-work/scripts/submit-work.controller.coffee
=> DEM-665 Update project submission logic

src/client/app/scripts/project-details.routes.js
Requires new bower install
ping @appirio-tech/demandside
=> remove status from copilot project routing

app/app.module.coffee, app/js-files.jade, app/scripts/timeline.controller.coffee, app/views/timeline.jade
=> [DEM-1023] create page for timeline directive

app/app-config.coffee, app/js-files.jade, app/scripts/file-detail.controller.coffee, app/scripts/generic-submissions-page.controller.cofee, app/scripts/generic-submissions-page.controller.coffee, app/views/file-detail.jade, app/views/submissions-generic.jade, app/views/timeline.jade
=> DEM-1247 Update Submissions Routes

app/app-run.coffee
@aselbie @vietnogi @samsep Watch out!!  Here i come....
=> Adding redirects by params
